### ISSUE TITLE
Demo page unavailable

### ISSUE THREAD

**Issue by wolfika** [krestaino/nuepress#13]
Upon opening the demo website, I get a 502 Bad Gateway error from nginx.

Screenshot: https://i.imgur.com/6IBa6Gy.png

**Comment by krestaino** [comment]
Back online! Sorry bout that and thanks for the heads up.

**Comment by iamdubx** [comment]
Sorry for flood, but I just want to say: **WOW**. Thanks for this awesomeness @krestaino

**Comment by krestaino** [comment]
@iamdubx Thanks for the kind words! :)
