### ISSUE TITLE
Menu from rest api

### ISSUE THREAD

**Issue by yashha** [krestaino/nuepress#32]
Maybe getting menu from rest api
https://github.com/unfulvio/wp-api-menus

**Comment by abdokouta** [comment]
hello, i have figure out the menu thing but what i need help with the the sub menu like is there is any method to query about it like ishaveChildren or Children.Length or something like that and also how to listed ?

**Comment by yashha** [comment]
Did you found a solution?
Did you look into the v2 of the menu api?
https://github.com/unfulvio/wp-api-menus/blob/master/includes/wp-api-menus-v2.php#L147
https://github.com/unfulvio/wp-api-menus/blob/master/includes/wp-api-menus-v2.php#L194

**Comment by abdokouta** [comment]
> Did you found a solution?
> Did you look into the v2 of the menu api?
> https://github.com/unfulvio/wp-api-menus/blob/master/includes/wp-api-menus-v2.php#L147
> https://github.com/unfulvio/wp-api-menus/blob/master/includes/wp-api-menus-v2.php#L194

yes i have checked but what about the render method like how to detect if the <li> has child how to nest those children underneath the parent i know that it by Parent ID and child orderID but how to get all parts together in one simple code. i have also looked at that resource 
https://stackoverflow.com/questions/51933430/vue-js-navigation-sub-menus-via-wp-rest-api

**Comment by yashha** [comment]
To achive  ishaveChildren or Children.Length you have to step between. fetching and displaying
https://stackoverflow.com/questions/51933430/vue-js-navigation-sub-menus-via-wp-rest-api#comment90885076_51944970

Maybe I don't understand the problem yet

**Comment by abdokouta** [comment]
How to achieve that with vuejs ?

**Comment by yashha** [comment]
You could fill your navItems property as an multidimensional array in the right structure. (menu items/ sub items)

https://codepen.io/JosephAllen/pen/zLQqRr?editors=0011
https://www.oreilly.com/library/view/javascript-cookbook/9781449390211/ch05s03.html

Then loop over it. You can then also ask for the length of the array.

**Comment by abdokouta** [comment]
@yashha, thanks so much i will give it a try and i will let u know

**Comment by abdokouta** [comment]
> @yashha, thanks so much i will give it a try and i will let u know

Here is a PEN 
https://codepen.io/abdokouta/pen/KGqwyV/
the parents work fine the children didn't show

**Comment by yashha** [comment]
https://codepen.io/anon/pen/aRwmxY

**Comment by abdokouta** [comment]
@yashha hello again, i have concern about how to implement the codpen example with this html structure 

`              <li class="classic">
                <a href="javascript:;">
                    Elements  <i class="pg-arrow_minimize m-l-5"></i>
                  </a>
                <nav class="classic ">
                  <span class="arrow"></span>
                  <ul>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#color" target="_blank">Colors</a>
                    </li>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#icons" target="_blank">Icons</a>
                    </li>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#buttons" target="_blank">Buttons</a>
                    </li>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#modals" target="_blank">Modals</a>
                    </li>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#progress_bars" target="_blank">Progress &amp; Activity</a>
                    </li>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#accordians" target="_blank">Accordians</a>
                    </li>
                    <li>
                      <a href="http://pages.revox.io/frontend/1.0/doc/#tabs" target="_blank">Tabs</a>
                    </li>
                  </ul>
                </nav>
              </li>`

could u help please?
