### ISSUE TITLE
How to enable direct url links?

### ISSUE THREAD

**Issue by jzucadi** [krestaino/nuepress#34]
How were you able to your website to work with direct url links? 

When you type in a url to a particular page or article, the routing works correctly. I haven't been able to achieve this. When I try to manually type in a link a page or article it shows me the home page without the data loaded. Routing only works when I load the homepage and navigate through the components.

**Comment by krestaino** [comment]
How are you running the app? Are you using `npm generate`?

**Comment by jzucadi** [comment]
Yes, npm run generate and then I tested it on some static hosting (Surge and S3) and it works fine when clicking on components to navigate. Its just when I try and manually put in the URL to a specific page that it returns the home page minus the data loaded

**Comment by jzucadi** [comment]
You aren't doing anything extra with routing? All i am doing is downloading the repo and hitting "npm run generate"

**Comment by yashha** [comment]
I believe you have to serve it locally using something like http-server
https://www.npmjs.com/package/http-server

**Comment by jzucadi** [comment]
I am not having issues serving the site locally. I'm talking when it's actually put live, on static hosting. On live static hosting, the routing only works if you are navigating through the menu, or links on the page. The routing does not work when you type in the url to a page. This sends you to the index.html but the data isn't loaded and the site is unusable without hitting refresh.

**Comment by krestaino** [comment]
I haven't tested NuePress at all with static hosting.

I wonder if this will work.

https://router.vuejs.org/en/essentials/history-mode.html#example-server-configurations

**Comment by jzucadi** [comment]
Thanks, yea I think its a server issue and less to do with the actual properties of vue-router.
